/* ═══════════════════════════════════════════════
   js/config.js — Auto-generated by build.js
   DO NOT edit this file manually.
   Change credentials via Render Environment Variables.
   Generated: 2026-04-26T04:45:22.619Z
═══════════════════════════════════════════════ */
window.__AERIALERP_CONFIG__ = {
  seedUsers: [
    {
      username:     'admin',
      passwordHash: '5cd3670caa1208e9cc384ce76bb17eeac7e5114da42709b3e3c7492df736bdac',
      role:         'admin',
      name:         '系統管理員',
      active:       true
    },
    {
      username:     'sales1',
      passwordHash: 'b9373fc7cd0b21f8be2775c18be6d732e54e16a559b530d067ab7022e9cd3d43',
      role:         'sales',
      name:         '業務員甲',
      active:       true
    },
    {
      username:     'tech1',
      passwordHash: '8135745e7aa3022a4d22f8defc90c096fb227dc42ae5161b13975db5c014b26c',
      role:         'technician',
      name:         '技師',
      active:       true
    },
  ],
  emailjsServiceId:  '',
  emailjsTemplateId: '',
  emailjsPublicKey:  '',
};
