/**
 * build.js — AerialERP Build Script
 * Reads Render environment variables and generates js/config.js
 * with pre-hashed passwords (SHA-256 + salt), matching browser crypto.subtle
 *
 * Run: node build.js
 * Env vars: ADMIN_USERNAME, ADMIN_PASSWORD,
 *           SALES_USERNAME,  SALES_PASSWORD,
 *           TECH_USERNAME,   TECH_PASSWORD
 */
const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

const SALT = '_aerial_salt_2026';
const hash = pwd => crypto.createHash('sha256').update(pwd + SALT).digest('hex');

// Read from env, fallback to defaults
const cfg = {
  admin: {
    username: process.env.ADMIN_USERNAME || 'admin',
    password: process.env.ADMIN_PASSWORD || 'admin1234',
    name:     process.env.ADMIN_NAME     || '系統管理員',
  },
  sales: {
    username: process.env.SALES_USERNAME || 'sales1',
    password: process.env.SALES_PASSWORD || 'sales1234',
    name:     process.env.SALES_NAME     || '業務員甲',
  },
  tech: {
    username: process.env.TECH_USERNAME  || 'tech1',
    password: process.env.TECH_PASSWORD  || 'tech1234',
    name:     process.env.TECH_NAME      || '技師',
  },
};

const output = `/* ═══════════════════════════════════════════════
   js/config.js — Auto-generated by build.js
   DO NOT edit this file manually.
   Change credentials via Render Environment Variables.
   Generated: ${new Date().toISOString()}
═══════════════════════════════════════════════ */
window.__AERIALERP_CONFIG__ = {
  seedUsers: [
    {
      username:     '${cfg.admin.username}',
      passwordHash: '${hash(cfg.admin.password)}',
      role:         'admin',
      name:         '${cfg.admin.name}',
      active:       true
    },
    {
      username:     '${cfg.sales.username}',
      passwordHash: '${hash(cfg.sales.password)}',
      role:         'sales',
      name:         '${cfg.sales.name}',
      active:       true
    },
    {
      username:     '${cfg.tech.username}',
      passwordHash: '${hash(cfg.tech.password)}',
      role:         'technician',
      name:         '${cfg.tech.name}',
      active:       true
    },
  ]
};
`;

const outPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log('✅ AerialERP build.js: js/config.js generated successfully');
console.log(`   Admin  : ${cfg.admin.username}`);
console.log(`   Sales  : ${cfg.sales.username}`);
console.log(`   Tech   : ${cfg.tech.username}`);
