services:
  - type: web
    name: aerialerp
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /sw.js
        name: Service-Worker-Allowed
        value: /
